src/Entity/Couture.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\CoutureRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;

use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;


/**
 * @ORM\Entity(repositoryClass=CoutureRepository::class)
 * @ORM\HasLifecycleCallbacks
 * @UniqueEntity(
 *  fields={"title"},
 *  message="Un autre produit possède déjà ce titre, merci de le modifier"
 * )
 */
class Couture
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=10, max=255, 
     *  minMessage="Le titre doit faire plus de 10 caractères",
     *  maxMessage="Le titre ne peut pas faire  plus de  255 caractères !")
     */
    private $title;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=20, minMessage="Votre introduction doit faire plus de 20 caractères")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=100, minMessage="Votre description ne doit pas faire plus de 100 caractères")
     */
    private $content;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Url()
     */
    private $coverImage;

    /**
     * @ORM\OneToMany(targetEntity=ImageCouture::class, mappedBy="couture", orphanRemoval=true)
     * @Assert\Valid()
     */
    private $imageCoutures;

    /**
     * @ORM\ManyToOne(targetEntity=User::class, inversedBy="coutures")
     * @ORM\JoinColumn(nullable=false)
     */
    private $author;

    /**
     * @ORM\OneToMany(targetEntity=CommentC::class, mappedBy="couture", orphanRemoval=true)
     */
    private $commentCs;

    public function __construct()
    {
        $this->imageCoutures = new ArrayCollection();
        $this->commentCs = new ArrayCollection();
    }

    /**
     * Permet d'initialiser le Slug !
     *
     * @ORM\PrePersist
     * @ORM\PreUpdate
     *
     * @return void
     */
    public function initializeSlug()
    {
        if (empty($this->slug)) {
            $slugify = new Slugify();
            $this->slug = $slugify->slugify($this->title);
        }
    }


    /**
     * Permet de récupérer le commentaire d'un auteur par rapport à un produit Bijoux
     *
     * @param User $author
     * @return CommentC|null
     */
    public function getCommentCFromAuthor(User $author)
    {
        // on boucle sur le tableau de commentaires pour chaque commentaire que j'ai dans cette produit
        foreach ($this->commentCs as $commentC) {
            // si l'auteur de commentaire se le meme que ici alors je veut returne ce commentaire
            if ($commentC->getAuthor() === $author) return $commentC;
        }
        // si non on returne null veut que il a pas encore commenter ce produit
        return null;
    }

    /**
     * Permet de faire la moyenne de notes reçu 
     *
     * @return void
     */
    public function getAvgRatings()
    {
        // Calculer la somme des notations
        $sum = array_reduce($this->commentCs->toArray(), function ($total, $commentC) {
            return $total + $commentC->getRating();
        }, 0);

        //  Faire le division pour avoir la moyenne
        if (count($this->commentCs) > 0) return $sum / count($this->commentCs);

        return 0;
    }



    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCoverImage(): ?string
    {
        return $this->coverImage;
    }

    public function setCoverImage(string $coverImage): self
    {
        $this->coverImage = $coverImage;

        return $this;
    }

    /**
     * @return Collection|ImageCouture[]
     */
    public function getImageCoutures(): Collection
    {
        return $this->imageCoutures;
    }

    public function addImageCouture(ImageCouture $imageCouture): self
    {
        if (!$this->imageCoutures->contains($imageCouture)) {
            $this->imageCoutures[] = $imageCouture;
            $imageCouture->setCouture($this);
        }

        return $this;
    }

    public function removeImageCouture(ImageCouture $imageCouture): self
    {
        if ($this->imageCoutures->removeElement($imageCouture)) {
            // set the owning side to null (unless already changed)
            if ($imageCouture->getCouture() === $this) {
                $imageCouture->setCouture(null);
            }
        }

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    /**
     * @return Collection|CommentC[]
     */
    public function getCommentCs(): Collection
    {
        return $this->commentCs;
    }

    public function addCommentC(CommentC $commentC): self
    {
        if (!$this->commentCs->contains($commentC)) {
            $this->commentCs[] = $commentC;
            $commentC->setCouture($this);
        }

        return $this;
    }

    public function removeCommentC(CommentC $commentC): self
    {
        if ($this->commentCs->removeElement($commentC)) {
            // set the owning side to null (unless already changed)
            if ($commentC->getCouture() === $this) {
                $commentC->setCouture(null);
            }
        }

        return $this;
    }
}

src/Entity/User.php
<?php

namespace App\Entity;

use Cocur\Slugify\Slugify;
use Doctrine\ORM\Mapping as ORM;
use App\Repository\UserRepository;
use Doctrine\Common\Collections\Collection;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface;

use Symfony\Component\Validator\Constraints as Assert;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;


/**
 * @ORM\Entity(repositoryClass=UserRepository::class)
 * @ORM\HasLifecycleCallbacks()
 * @UniqueEntity(
 * fields={"email"},
 * message="Un autre utilisateur s'est déjà inscrit avec cette adresse email, merci de la modifier"
 * )
 */
class User implements UserInterface, PasswordAuthenticatedUserInterface
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Vous devez renseigner votre prénom")
     */
    private $firstName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\NotBlank(message="Vous devez renseigner votre nom de famille")
     */
    private $lastName;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Email(message="Veuillez renseigner un email valide !")
     */
    private $email;

    /**
     * @ORM\Column(type="string", length=255, nullable=true)
     * @Assert\Url(message="Veuillez donner une URL valide pour votre avatar !")
     */
    private $picture;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $hash;


    /**
     *
     * @Assert\EqualTo(propertyPath="hash",message="Vous n'avez pas correctement confirmé votre mot de passe !")
     * @var [type]
     */
    // Pour la Confirmation de mot de passe 2 eme champs de form
    public $passwordConfirm;

    /**
     * @ORM\Column(type="string", length=255)
     * @Assert\Length(min=10, minMessage="Votre introduction doit faire au moins 10 caractères")
     */
    private $introduction;

    /**
     * @ORM\Column(type="text")
     * @Assert\Length(min=100, minMessage="Votre description doit faire au moins 100 caractères")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $slug;

    /**
     * @ORM\OneToMany(targetEntity=Bijoux::class, mappedBy="author")
     */
    private $bijouxs;

    /**
     * @ORM\OneToMany(targetEntity=Couture::class, mappedBy="author")
     */
    private $coutures;

    /**
     * @ORM\ManyToMany(targetEntity=Role::class, mappedBy="users")
     */
    private $userRoles;

    /**
     * @ORM\OneToMany(targetEntity=CommentB::class, mappedBy="author", orphanRemoval=true)
     */
    private $commentBs;

    /**
     * @ORM\OneToMany(targetEntity=CommentC::class, mappedBy="author", orphanRemoval=true)
     */
    private $commentCs;


    
    public function getFullName() {
        // Renvoi une concatenation de nom et prenom
        return "{$this->firstName} {$this->lastName}";
    }

    /**
     * Permet d'initialiser le Slug !
     * @ORM\PrePersist
     * @ORM\PreUpdate
     * @return void
     */
    public function initializeSlug()
    {
        if (empty($this->slug)) {
            $slugify =  new Slugify();
            $this->slug = $slugify->slugify($this->firstName . ' ' . $this->lastName);
        }
    }


    public function __construct()
    {
        $this->bijouxs = new ArrayCollection();
        $this->coutures = new ArrayCollection();
        $this->userRoles = new ArrayCollection();
        $this->commentBs = new ArrayCollection();
        $this->commentCs = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getFirstName(): ?string
    {
        return $this->firstName;
    }

    public function setFirstName(string $firstName): self
    {
        $this->firstName = $firstName;

        return $this;
    }

    public function getLastName(): ?string
    {
        return $this->lastName;
    }

    public function setLastName(string $lastName): self
    {
        $this->lastName = $lastName;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getPicture(): ?string
    {
        return $this->picture;
    }

    public function setPicture(?string $picture): self
    {
        $this->picture = $picture;

        return $this;
    }

    public function getHash(): ?string
    {
        return $this->hash;
    }

    public function setHash(string $hash): self
    {
        $this->hash = $hash;

        return $this;
    }

    public function getIntroduction(): ?string
    {
        return $this->introduction;
    }

    public function setIntroduction(string $introduction): self
    {
        $this->introduction = $introduction;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    /**
     * @return Collection|Bijoux[]
     */
    public function getBijouxs(): Collection
    {
        return $this->bijouxs;
    }

    public function addBijoux(Bijoux $bijoux): self
    {
        if (!$this->bijouxs->contains($bijoux)) {
            $this->bijouxs[] = $bijoux;
            $bijoux->setAuthor($this);
        }

        return $this;
    }

    public function removeBijoux(Bijoux $bijoux): self
    {
        if ($this->bijouxs->removeElement($bijoux)) {
            // set the owning side to null (unless already changed)
            if ($bijoux->getAuthor() === $this) {
                $bijoux->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|Couture[]
     */
    public function getCoutures(): Collection
    {
        return $this->coutures;
    }

    public function addCouture(Couture $couture): self
    {
        if (!$this->coutures->contains($couture)) {
            $this->coutures[] = $couture;
            $couture->setAuthor($this);
        }

        return $this;
    }

    public function removeCouture(Couture $couture): self
    {
        if ($this->coutures->removeElement($couture)) {
            // set the owning side to null (unless already changed)
            if ($couture->getAuthor() === $this) {
                $couture->setAuthor(null);
            }
        }

        return $this;
    }

    public function getRoles()
    {
        $roles = $this->userRoles->map(function($role){
            return $role->getTitle();
        })->toArray();

        $roles[] = 'ROLE_USER';

        return $roles;
        // $roles = $this->roles;
        // // guarantee every user at least has ROLE_USER
        // $roles[] = 'ROLE_USER';

        // return array_unique($roles);
    }

    public function getPassword(): string
    {
        return $this->hash;
    }

    public function getSalt()
    {
    }

    public function getUsername()
    {
        return $this->email;
    }

    /**
     * The public representation of the user (e.g. a username, an email address, etc.)
     *
     * UserInterface
     */
    public function getUserIdentifier(): string
    {
        return (string) $this->email;
    }

    public function eraseCredentials()
    {
    }

    /**
     * @return Collection|Role[]
     */
    public function getUserRoles(): Collection
    {
        return $this->userRoles;
    }

    public function addUserRole(Role $userRole): self
    {
        if (!$this->userRoles->contains($userRole)) {
            $this->userRoles[] = $userRole;
            $userRole->addUser($this);
        }

        return $this;
    }

    public function removeUserRole(Role $userRole): self
    {
        if ($this->userRoles->removeElement($userRole)) {
            $userRole->removeUser($this);
        }

        return $this;
    }

    /**
     * @return Collection|CommentB[]
     */
    public function getCommentBs(): Collection
    {
        return $this->commentBs;
    }

    public function addCommentB(CommentB $commentB): self
    {
        if (!$this->commentBs->contains($commentB)) {
            $this->commentBs[] = $commentB;
            $commentB->setAuthor($this);
        }

        return $this;
    }

    public function removeCommentB(CommentB $commentB): self
    {
        if ($this->commentBs->removeElement($commentB)) {
            // set the owning side to null (unless already changed)
            if ($commentB->getAuthor() === $this) {
                $commentB->setAuthor(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection|CommentC[]
     */
    public function getCommentCs(): Collection
    {
        return $this->commentCs;
    }

    public function addCommentC(CommentC $commentC): self
    {
        if (!$this->commentCs->contains($commentC)) {
            $this->commentCs[] = $commentC;
            $commentC->setAuthor($this);
        }

        return $this;
    }

    public function removeCommentC(CommentC $commentC): self
    {
        if ($this->commentCs->removeElement($commentC)) {
            // set the owning side to null (unless already changed)
            if ($commentC->getAuthor() === $this) {
                $commentC->setAuthor(null);
            }
        }

        return $this;
    }
}

templates/couture/_collection.html.twig
{% block _couture_imageCoutures_widget %}
	<p>Ici, vous pouvez ajouter vos propres images !</p>

	{{ form_widget(form) }}

	{# inpute qui compte les images qui sont enregistre deja et leur valeur #}
	<input type="hidden" id="widgets-counter" value="0">

	<div class="form-group">
		<button type="button" id="add-imageCouture" class="btn btn-primary">
			<i class="fas fa-plus"></i>
			Ajouter une image
		</button>

	</div>
{% endblock %}


{% block _couture_imageCoutures_entry_row %}
	{{ form_widget(form) }}
{% endblock %}

{% block _couture_imageCoutures_entry_widget %}
	<div class="form-group" id="block_{{id}}">
		<div class="row">
			<div class="col-10">
				<div class="row">
					<div class="col">
						{{ form_widget(form.url) }}
						{{ form_errors(form.url) }}
					</div>
					<div class="col">
						{{ form_widget(form.caption) }}
						{{ form_errors(form.caption) }}
					</div>
				</div>
			</div>
			<div class="col-2">
				<button type="button" data-action="delete" data-target="#block_{{id}}" class="btn btn-danger">x</button>
			</div>
		</div>
	</div>
{% endblock %}

templates/couture/_couture.html.twig
{% set url = path('coutures_show', {'slug': couture.slug}) %}
<div class="col-md-4">
	<div class="card bg-light mb-3">
		<div class="card-header text-center">
			Nos céation couture,
			<strong>créer</strong>
			/ main
			<br>
			{% if couture.commentCs | length > 0 %}
				{% include "partials/rating.html.twig" with {"rating" : couture.avgRatings } %}
			{% else %}
			<small>Pas encore noté</small>
			{% endif %}
		</div>
		<a href="{{ url }}">
			<img src="{{ couture.coverImage }}" alt="" style="height: 200px; width: 100%; display: block">
		</a>

		<div class="card-body">
			<h4 class="card-title">
				<a href="{{ url }}">
					{{ couture.title }}
				</a>
			</h4>
			<p class="card-text">
				{{ couture.introduction }}
			</p>
			<a href="{{ url }}" class="btn btn-primary float-right">En savoir plus !</a>

			{# si utilisateur connecter et si l'author de produit alors on affiche le button #}
			{% if app.user and app.user == couture.author %}
				<a href="{{ path('coutures_edit', {'slug': couture.slug}) }}" class="btn btn-secondary">Modifier le produit</a>
			{% endif %}


		</div>
	</div>
</div>

templates/couture/edit.html.twig
{% extends "base.html.twig" %}

{% block title %}Edition d'un produit
{% endblock %}

{% form_theme form 'couture/_collection.html.twig' %}

{% block body %}

	<div class="container">
		<h1>Modifier l'produit :
			{{ couture.title }}</h1>

		{{ form_start(form) }}

		{{ form_widget(form) }}

		<button type="submit" class="btn btn-primary">Enregistrer les modifications</button>

		{{ form_end(form) }}
	</div>

{% endblock %}


{% block javascripts %}
	<script type="text/javascript" src="/js/couture.js"></script>
{% endblock %}

templates/couture/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nos magnifiques creation en couture!
{% endblock %}

{% block body %}
	<div class="container">
		<h1 class="my-5">Voici nos creation en couture!</h1>

		<div
			class="row">
			{# Boucle fort pour chaque produit couture dans le tableaux de produits de coutures #}
			{% for couture in coutures %}
				{% include "couture/_couture.html.twig" %}
			{% endfor %}
		</div>
	</div>
{% endblock %}

templates/couture/new.html.twig
{% extends "base.html.twig" %}

{% block title %}Création d'un produit Couture
{% endblock %}

{# on dit ici avec {% form_theme form _self %} a twig que on veut utiliser cette theme 
qui et ici dans cette page pour notre affichage #}
{% form_theme form 'couture/_collection.html.twig' %}

{% block body %}

	<div class="container">
		<h1>Créer un nouveaux produit Couture</h1>

		{{ form_start(form) }}
		
		<div class="row">
			<div class="col-md-4">
				<div class="alert alert-light">
					<h2>Informations générales</h2>
					<hr>
					{{ form_row(form.title) }}
					{{ form_row(form.slug) }}
				</div>

				<div class="alert alert-light">
					<h2>Détails d'produit</h2>
					<hr>
					{{ form_row(form.introduction) }}
					{{ form_row(form.content) }}
				</div>
			</div>
			<div class="col-md-8">
				<div class="alert alert-light">
					<h2>Images de produit</h2>
					<hr>
					{{ form_row(form.coverImage) }}
					{{ form_row(form.imageCoutures) }}
				</div>
			</div>
		</div>
	{# {{ form_widget(form) }} #}
		<div class="alert alert-info clearfix">

			<h2 class="alert-heading">
				<i class="fas fa-save"></i>
				Sauvgarder le produit
			</h2>

			<p>Vous étes sur le point de créer votre produit... !</p>
			<button type="submit" class="btn btn-primary float-right">
				<i class="fas fa-check"></i>
				Créer un produit Couture</button>
		</div>
		{{ form_end(form) }}
	</div>

{% endblock %}

{% block javascripts %}
	<script src="/js/couture.js"></script>
{% endblock %}

templates/couture/show.html.twig
{% extends "base.html.twig" %}

{% block title %}
	couture.title
{% endblock %}

{% block body %}
	<div class="couture-title" style="background-image: url({{ couture.coverImage }})">
		<div class="container mb-3">
			<h1>{{ couture.title }}</h1>
			<p>{{ couture.introduction }}</p>
			<a href="#" class="btn btn-primary">Nos contacter</a>

			{# si utilisateur connecter et si l'author de produit alors on affiche le button #}
			{% if app.user and app.user == couture.author %}
				<a href="{{ path('coutures_edit', {'slug': couture.slug}) }}" class="btn btn-secondary">Modifier le produit</a>

				<a href="{{ path('coutures_delete', {'slug': couture.slug}) }}" class="btn btn-danger" onclick="return confirm(`Êtes vous sur de vouloir supprimer l'produit : {{couture.title}} ?`)">Supprimer l'produit</a>
			{% endif %}

		</div>
	</div>

	<div class="container">
		<div class="row">
			<div class="col-md-8 mb-3">
				{{ couture.content | raw }}

				{# Carulssel image #}
				<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">

					<ol class="carousel-indicators">
						{% for imageCouture in couture.imageCoutures %}
							<li data-target="#carouselExampleIndicators" data-slide-to="{{ loop.index0 }}" {% if loop.first %} class="active{% endif %}"></li>
						{% endfor %}

					</ol>

					<div class="carousel-inner">
						{% for imageCouture in couture.imageCoutures %}
							<div class="carousel-item {% if loop.first %}active{% endif %}">
								<img src="{{ imageCouture.url }}" class="d-block w-100" alt="...">
								<div class="carousel-caption d-none d-md-block">
									<h5>{{ couture.title }}</h5>
									<p>{{ imageCouture.caption }}</p>
								</div>
							</div>
						{% endfor %}
					</div>

					<a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
						<span class="carousel-control-prev-icon" aria-hidden="true"></span>
						<span class="sr-only">Previous</span>
					</a>
					<a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
						<span class="carousel-control-next-icon" aria-hidden="true"></span>
						<span class="sr-only">Next</span>
					</a>
				</div>

			<hr>


            {# Boucle pour les commentaire COUTURE #}
			{% if couture.commentCs | length > 0 %}
				<h2 class="mb-3">Commentaire de nos visiteurs :</h2>
				
				<div class="alert alert-info">
					<h4 class="alert-heading text-center">
						<div class="row align-items-center">
							<div class="col">
								Note globale donnée par nos visiteurs
							</div>
							<div class="col">
								{# Les Etoiles #}
								{# {% set rating = commentC.rating %} #}
								{% include "partials/rating.html.twig" with {"rating" : couture.avgRatings } %}
						<br>
								<small>(Calculée sur {{ couture.commentCs | length }} avis)</small>
							
							</div>
						</div>
					</h4>
				</div>
				
				{% for commentC in couture.commentCs %}
					<div class="bg-light rounded mb-3 py-3 px-3">
						<strong>{{ commentC.author.firstName }}</strong> a dit :
						<blockquote>
							{{ commentC.content }}
						</blockquote>
						<strong>Note donnée par :</strong> 
					    
						{# Les Etoiles #}

						{# {% set rating = commentB.rating %} #}
						{% include "partials/rating.html.twig" with {"rating" : commentC.rating} %}
					
					</div>
				{% endfor %}
			{% else %}
				<h2>Ce produit n'a pas encore reçu de commentaires ...</h2>
			{% endif %}

			{# Formulaire commentaires lese #}
			<div class="aler alert-light">
				<h2 class="alert-heading">Votre avis compte !</h2>
					{% set commentC = couture.commentCFromAuthor(app.user) %}

				{% if commentC is not null %}
					<blockquote>
						{{ commentC.content }}
					</blockquote>

					<strong>Note :</strong>
					{% include 'partials/rating.html.twig' with {'rating' : commentC.rating} %}
				{% else %}
					{{ form_start(form) }}
					{{ form_widget(form) }}
					<button type="submit" class="btn btn-success mt-3">Confirmer !</button>
					{{ form_end(form) }}

				{% endif %}
			</div>
			</div>

</div>
			<div
				class="col">
				{#  variable a = author #}
				{% set a = couture.author %}

				<div class="row mb-3 align-items-center">
					<div
						class="col-3">
						{# Avatar de {{a.fullName}} #}
						<a href="{{ path('user_show', {'slug': a.slug}) }}">
							<img src="{{a.picture}}" class="avatar avatar-medium" alt="avatar de {{a.fullName}}">
						</a>
					</div>

					<div class="col">
						<a href="{{ path('user_show', {'slug': a.slug}) }}">
							<h3>{{ a.fullName }}
							</h3>
						</a>
						<span class="badge bg-primary">{{ a.coutures | length }}
							produits
						</span>
					</div>

				</div>

				{{ a.description | raw }}
			</div>
		</div>
	</div>
{% endblock %}